try to fix the crash
Attempt to correct the crash caused by a user connecting in the channels and immediately zline on connection: jbnc crash !

> :irc.s.com 465 Brigitte_1 :You are not welcome on this server. Z-Lined: connection refused. Email support@s.com for more information.
> :irc.s.com NOTICE Brigitte_1 :You are not welcome on this server. Z-Lined: connection refused. Email support@s.com for more information.
> ERROR :Closing Link: Brigitte_1[197.xxxx] (Banned (Z-Lined): connection refused)
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
> @time=2020-08-01T11:14:39.935Z;msgid=Onnn4u7tq88ob4CbHKl4Ha-4ODE5ntxOSpzVeK8H6wWMQ;account=Brigitte_1 :Brigitte_1!o-accGNmERAtY7W@57889B7B.2A9D02DA.AC8109B2.IP JOIN :#quizz
<JOIN #+18ans
<JOIN #25-35ans
<JOIN #35-45ans
/home/debian/node/jbnc/bouncer.js:508
                  if(typeof connections[this.hash].channels !== 'undefined' && connections[this.hash].channels[channels[m].trim().toUpperCase()]) {
                                                   ^

TypeError: Cannot read property 'channels' of undefined
    at TLSSocket.<anonymous> (/home/debian/node/jbnc/bouncer.js:508:52)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
root@vps-871a4996:/home/debian/node/jbnc#



[13:14:39] -irc.s.com- *** Client connecting: Brigitte_1 (o-accGNmERAtY7W@197.2xxxx) [197.2xxxxxxx] {clients} [secure ECDHE-RSA-AES256-GCM-SHA384]
[13:14:39] -irc.s.com- *** Z-Line added for *@197.234.xxxon Sat Aug  1 11:14:39 2020 GMT (from Sysop!SysOp@xxx.xxxxx to expire at Sun Aug  2 11:14:39 2020 GMT: connection refused)
[13:14:39] -irc.s.com- *** Client exiting: Brigitte_1 (o-accGNmERAtY7W@197.xxxx] (Banned (Z-Lined): connection refused)
[13:14:39] -irc.s.com- *** Client exiting: Berenice (o-act03813df18559144@92.xxxxx] [4E36085B.7CFCF9D0.D9B694E0.IP] (Read error)
[13:14:39] -irc.s.com- *** Client exiting: Zeizei221 (o-act3de4bea06618038@41.8xxxxx] [EEC69552.8C631F99.6820547C.IP] (Read error)
[13:14:39] -irc.s.com- *** Client exiting: TheMagician (o-act7bab16d8c5b1eae@84.78.xxxxxx] [EB7B0A4E.78A9C044.A5E6209F.IP] (Read error)
[13:14:39] -irc.s.com- *** Client exiting: sahrawi_casa (o-act0214e72c5a36b02@105.6xxxxx1CA0.IP] (Read error)
[13:14:39] -irc.s.com- *** Client exiting: Mario66 (o-act67f571bde37cddf@96.21.178xxxxxx] (Read error)
[13:14:39] -irc.s.com- *** Client exiting: MrSobad (o-actca92532bda60cde@184.1xxxxxxx] (Read error)
[13:14:39] -irc.s.com- *** Client exiting: elegance63 (o-accrebzTGIiow@41.1xxxxxx] (Read error)