a crash
Cause this crash as soon as you enter a channel and / or leave immediately (less than a second later)

Error:
 > :irc.s.com 354 Tetelle #35-45ans irclog logs-canaux.s.com irc.s.com Botlog HrsB 0 Botlog n/a :20/H/FR
 > :irc.s.com 315 Tetelle #35-45ans :End of /WHO list.
 > :irc.s.com 353 Miky = #15-25ans :
 /home/mima/node/jbnc/bouncer.js:1197
                    this.channels[_channel].userhosts.push("*@*");
                                                      ^

TypeError: Cannot read property 'push' of undefined
    at TLSSocket.<anonymous> (/home/mima/node/jbnc/bouncer.js:1197:55)