Update of gone with error .end();
Example error : 

            connections[this.hash].gone=setTimeout(function(x){connections[x].end(); delete connections[x]; },BOUNCER_TIMEOUT*1000,this.hash);
                                                                              ^

TypeError: Cannot read property 'end' of undefined