Update of change-me
Causes this bug:

                    this.channels[_channel].userhosts.push(_names[x].trim().split("!")[1]);
                                                      ^

                    TypeError: Cannot read property 'push' of undefined